default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3
  #url: <%= Rails.application.credentials.database_url %>

# not currently using this
test:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>

production:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>
