default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rolled_notes_development
  user: -HIDE-
  password: -HIDE-

test:
  <<: *default
  database: rolled_notes_test

production:
  <<: *default
  database: rolled_notes_production
  user: -HIDE-
  password: -HIDE-
  # password: <%= ENV["ROLLED_NOTES_DATABASE_PASSWORD"] %>
  # url: postgresql://-HIDE-:-HIDE-@192.168.XXX.XXX:PPPP/rolled_notes_production